"use client";

import { useState, useEffect, useCallback } from "react";
import { OcBadge } from "@/components/shared";
import {
  User,
  Download,
  Sparkles,
  Mic,
  Palette,
  MessageSquare,
  Eye,
  ChevronDown,
} from "lucide-react";

interface Character {
  id: string;
  name: string;
  description: string;
  stylePrompt: string;
  niche: string | null;
  referenceImages: string[];
  isActive: boolean;
  profile?: CharacterProfile | null;
}

interface CharacterProfile {
  id: string;
  voiceProfile: string | null;
  voiceModelId: string | null;
  colorPalette: string[];
  catchphrases: string[];
  personalityTraits: string[];
  doList: string[];
  dontList: string[];
  speakingStyle: string | null;
  visualStyle: string | null;
  consistencyScore: number;
  totalAppearances: number;
  lastUsedAt: string | null;
}

export default function MediaKitPage() {
  const [characters, setCharacters] = useState<Character[]>([]);
  const [selectedId, setSelectedId] = useState<string>("");
  const [generating, setGenerating] = useState(false);
  const [mediaKitText, setMediaKitText] = useState<string | null>(null);

  const fetchCharacters = useCallback(async () => {
    const res = await fetch("/api/characters").then((r) => r.json()).catch(() => ({ characters: [] }));
    const chars = res.characters || [];
    setCharacters(chars);
    if (chars.length > 0 && !selectedId) {
      setSelectedId(chars[0].id);
    }
  }, [selectedId]);

  useEffect(() => { fetchCharacters(); }, [fetchCharacters]);

  // Fetch full profile when character is selected
  const [fullChar, setFullChar] = useState<Character | null>(null);
  useEffect(() => {
    if (!selectedId) { setFullChar(null); return; }
    const basic = characters.find((c) => c.id === selectedId);
    if (!basic) { setFullChar(null); return; }

    // Try to fetch profile and merge with character data
    fetch(`/api/characters/${selectedId}/profile`)
      .then((r) => r.json())
      .then((data) => {
        setFullChar({ ...basic, profile: data.profile || null });
      })
      .catch(() => {
        setFullChar({ ...basic, profile: null });
      });
    setMediaKitText(null);
  }, [selectedId, characters]);

  const generateMediaKit = async () => {
    if (!fullChar) return;
    setGenerating(true);
    // Build a shareable summary from the character data
    const profile = fullChar.profile;
    const lines = [
      `=== ${fullChar.name} - AI Model Media Kit ===`,
      "",
      `Niche: ${fullChar.niche || "General"}`,
      `Description: ${fullChar.description || "N/A"}`,
      "",
      "--- Personality ---",
      `Traits: ${profile?.personalityTraits?.join(", ") || "Not configured"}`,
      `Speaking Style: ${profile?.speakingStyle || "Not configured"}`,
      `Catchphrases: ${profile?.catchphrases?.join(" | ") || "None"}`,
      "",
      "--- Voice Profile ---",
      `Voice: ${profile?.voiceProfile || "Default"}`,
      `Voice Model: ${profile?.voiceModelId || "edge-tts"}`,
      "",
      "--- Visual Identity ---",
      `Style: ${profile?.visualStyle || fullChar.stylePrompt || "Not configured"}`,
      `Color Palette: ${profile?.colorPalette?.join(", ") || "Not set"}`,
      "",
      "--- Performance ---",
      `Consistency Score: ${profile?.consistencyScore?.toFixed(0) || "100"}%`,
      `Total Appearances: ${profile?.totalAppearances || 0}`,
      `Last Used: ${profile?.lastUsedAt ? new Date(profile.lastUsedAt).toLocaleDateString() : "Never"}`,
      "",
      "--- Brand Guidelines ---",
      `Always: ${profile?.doList?.join(", ") || "Be authentic"}`,
      `Never: ${profile?.dontList?.join(", ") || "Break character"}`,
      "",
      `Generated by OpenClaw | ${new Date().toISOString().split("T")[0]}`,
    ];
    setMediaKitText(lines.join("\n"));
    setGenerating(false);
  };

  const selected = fullChar;
  const profile = selected?.profile;

  return (
    <div className="flex flex-col gap-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <span className="text-page-title text-oc-text">Media Kit</span>
          <OcBadge label="AI Talent Portfolio" color="#DB2777" bg="#FDF2F8" />
        </div>
        <div className="flex items-center gap-2">
          {/* Character Selector */}
          <div className="relative">
            <select
              value={selectedId}
              onChange={(e) => setSelectedId(e.target.value)}
              className="text-small px-3 py-1.5 pr-8 border border-oc-border rounded-oc bg-oc-card text-oc-text appearance-none cursor-pointer"
            >
              {characters.length === 0 && <option value="">No characters</option>}
              {characters.map((c) => (
                <option key={c.id} value={c.id}>{c.name}{c.niche ? ` (${c.niche})` : ""}</option>
              ))}
            </select>
            <ChevronDown className="w-3.5 h-3.5 text-oc-text-muted absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" />
          </div>
        </div>
      </div>

      {!selected ? (
        <div className="p-8 bg-oc-card border border-oc-border rounded-oc text-center">
          <User className="w-8 h-8 text-oc-text-muted mx-auto mb-3" />
          <div className="text-small text-oc-text-muted">No characters found. Create a character first to generate a media kit.</div>
        </div>
      ) : (
        <>
          {/* Character Overview Card */}
          <div className="p-5 bg-oc-card border border-oc-border rounded-oc">
            <div className="flex gap-5">
              {/* Avatar / Image */}
              <div className="w-24 h-24 rounded-oc bg-gradient-to-br from-pink-100 to-purple-100 flex items-center justify-center shrink-0">
                {selected.referenceImages.length > 0 ? (
                  <img
                    src={selected.referenceImages[0]}
                    alt={selected.name}
                    className="w-full h-full rounded-oc object-cover"
                  />
                ) : (
                  <User className="w-10 h-10 text-purple-300" />
                )}
              </div>

              <div className="flex-1">
                <div className="flex items-center gap-2.5 mb-1">
                  <span className="text-[18px] font-bold text-oc-text">{selected.name}</span>
                  <OcBadge label="Available for Hire" color="#059669" bg="#ECFDF5" />
                  {selected.niche && <OcBadge label={selected.niche} color="#6B6560" bg="#F8F7F4" />}
                </div>
                <div className="text-small text-oc-text-muted mb-3">{selected.description || "No description set"}</div>

                {/* Quick Stats */}
                <div className="flex gap-4">
                  <div>
                    <div className="text-[20px] font-bold font-mono text-oc-text">{profile?.totalAppearances || 0}</div>
                    <div className="text-[9px] text-oc-text-muted uppercase">Appearances</div>
                  </div>
                  <div>
                    <div className="text-[20px] font-bold font-mono text-oc-purple">{profile?.consistencyScore?.toFixed(0) || 100}%</div>
                    <div className="text-[9px] text-oc-text-muted uppercase">Consistency</div>
                  </div>
                  <div>
                    <div className="text-[20px] font-bold font-mono text-oc-text">
                      {profile?.lastUsedAt ? new Date(profile.lastUsedAt).toLocaleDateString() : "Never"}
                    </div>
                    <div className="text-[9px] text-oc-text-muted uppercase">Last Active</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Profile Details Grid */}
          <div className="grid grid-cols-3 gap-3">
            {/* Personality Traits */}
            <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
              <div className="flex items-center gap-2 mb-3">
                <Sparkles className="w-4 h-4 text-purple-500" />
                <span className="text-small font-semibold text-oc-text">Personality Traits</span>
              </div>
              {profile?.personalityTraits && profile.personalityTraits.length > 0 ? (
                <div className="flex flex-wrap gap-1.5">
                  {profile.personalityTraits.map((trait) => (
                    <OcBadge key={trait} label={trait} color="#7C3AED" bg="#F5F3FF" />
                  ))}
                </div>
              ) : (
                <div className="text-tiny text-oc-text-muted">No traits configured</div>
              )}
            </div>

            {/* Voice Profile */}
            <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
              <div className="flex items-center gap-2 mb-3">
                <Mic className="w-4 h-4 text-amber-500" />
                <span className="text-small font-semibold text-oc-text">Voice Profile</span>
              </div>
              <div className="text-tiny text-oc-text-muted leading-relaxed">
                {profile?.voiceProfile || "Default voice configuration"}
              </div>
              {profile?.voiceModelId && (
                <div className="mt-2">
                  <OcBadge label={profile.voiceModelId} color="#D97706" bg="#FFFBEB" />
                </div>
              )}
            </div>

            {/* Visual Style */}
            <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
              <div className="flex items-center gap-2 mb-3">
                <Eye className="w-4 h-4 text-blue-500" />
                <span className="text-small font-semibold text-oc-text">Visual Style</span>
              </div>
              <div className="text-tiny text-oc-text-muted leading-relaxed">
                {profile?.visualStyle || selected.stylePrompt || "No visual style defined"}
              </div>
            </div>

            {/* Color Palette */}
            <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
              <div className="flex items-center gap-2 mb-3">
                <Palette className="w-4 h-4 text-pink-500" />
                <span className="text-small font-semibold text-oc-text">Color Palette</span>
              </div>
              {profile?.colorPalette && profile.colorPalette.length > 0 ? (
                <div className="flex gap-2">
                  {profile.colorPalette.map((hex, i) => (
                    <div key={i} className="flex flex-col items-center gap-1">
                      <div className="w-8 h-8 rounded-oc border border-oc-border" style={{ backgroundColor: hex }} />
                      <span className="text-[9px] font-mono text-oc-text-muted">{hex}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-tiny text-oc-text-muted">No palette set</div>
              )}
            </div>

            {/* Catchphrases */}
            <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
              <div className="flex items-center gap-2 mb-3">
                <MessageSquare className="w-4 h-4 text-teal-500" />
                <span className="text-small font-semibold text-oc-text">Catchphrases</span>
              </div>
              {profile?.catchphrases && profile.catchphrases.length > 0 ? (
                <div className="flex flex-col gap-1.5">
                  {profile.catchphrases.map((phrase, i) => (
                    <div key={i} className="text-tiny text-oc-text italic bg-oc-bg px-2 py-1 rounded-oc">
                      &quot;{phrase}&quot;
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-tiny text-oc-text-muted">No catchphrases set</div>
              )}
            </div>

            {/* Speaking Style */}
            <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
              <div className="flex items-center gap-2 mb-3">
                <MessageSquare className="w-4 h-4 text-indigo-500" />
                <span className="text-small font-semibold text-oc-text">Speaking Style</span>
              </div>
              <div className="text-tiny text-oc-text-muted leading-relaxed">
                {profile?.speakingStyle || "No specific speaking style defined"}
              </div>
            </div>
          </div>

          {/* Brand Guidelines */}
          {profile && (profile.doList?.length > 0 || profile.dontList?.length > 0) && (
            <div className="grid grid-cols-2 gap-3">
              <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
                <div className="text-small font-semibold text-oc-green mb-2">Always Do</div>
                {profile.doList.length > 0 ? (
                  <ul className="space-y-1">
                    {profile.doList.map((item, i) => (
                      <li key={i} className="text-tiny text-oc-text flex items-start gap-1.5">
                        <span className="text-oc-green mt-0.5">+</span> {item}
                      </li>
                    ))}
                  </ul>
                ) : (
                  <div className="text-tiny text-oc-text-muted">No rules set</div>
                )}
              </div>
              <div className="p-4 bg-oc-card border border-oc-border rounded-oc">
                <div className="text-small font-semibold text-red-500 mb-2">Never Do</div>
                {profile.dontList.length > 0 ? (
                  <ul className="space-y-1">
                    {profile.dontList.map((item, i) => (
                      <li key={i} className="text-tiny text-oc-text flex items-start gap-1.5">
                        <span className="text-red-500 mt-0.5">-</span> {item}
                      </li>
                    ))}
                  </ul>
                ) : (
                  <div className="text-tiny text-oc-text-muted">No rules set</div>
                )}
              </div>
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-3">
            <button
              onClick={generateMediaKit}
              disabled={generating}
              className="flex items-center gap-1.5 px-4 py-2 bg-oc-text text-white rounded-oc text-small font-semibold hover:opacity-90 disabled:opacity-50"
            >
              <Sparkles className="w-3.5 h-3.5" />
              {generating ? "Generating..." : "Generate Media Kit"}
            </button>
            <button
              onClick={() => {
                if (mediaKitText) {
                  const blob = new Blob([mediaKitText], { type: "text/plain" });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = `${selected.name.replace(/\s+/g, "-")}-media-kit.txt`;
                  a.click();
                  URL.revokeObjectURL(url);
                }
              }}
              disabled={!mediaKitText}
              className="flex items-center gap-1.5 px-4 py-2 border border-oc-border text-oc-text rounded-oc text-small font-semibold hover:bg-oc-bg disabled:opacity-50"
            >
              <Download className="w-3.5 h-3.5" />
              Download PDF
            </button>
          </div>

          {/* Generated Media Kit Preview */}
          {mediaKitText && (
            <div className="p-4 bg-oc-bg border border-oc-border rounded-oc">
              <div className="text-[9px] font-semibold text-oc-text-muted uppercase mb-2">Generated Media Kit Preview</div>
              <pre className="text-tiny text-oc-text font-mono whitespace-pre-wrap leading-relaxed">{mediaKitText}</pre>
            </div>
          )}
        </>
      )}
    </div>
  );
}
